#!/usr/bin/env python3
"""GVSoC power-hook executable backed by a running 3D-ICE simulation.

GVSoC invokes this program directly for init, update, and final exchanges.
Static component/floorplan mappings come from the architecture-owned system
contract. Per-run paths come from a small hook configuration generated by the
co-simulation launcher.
"""

import argparse
import csv
import json
import math
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
INTERFACE_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(INTERFACE_DIR))
sys.path.insert(0, str(SCRIPT_DIR))

from ice_trace_adapter import (  # noqa: E402
    adapt_slot,
    build_power_sources,
    parse_floorplan_entries,
    validate_floorplan_entries,
    write_slot,
)
from system_contract import (  # noqa: E402
    flattened_floorplan_name,
    floorplan_elements,
    geometry_entry,
    initial_temperature_c,
    load_contract,
    power_columns,
    thermal_components,
)


PROTOCOL_NAME = "gvsoc-power-hook"
PROTOCOL_VERSION = 1
HOOK_CONFIG_NAME = "3dice-gvsoc-power-hook"
HOOK_CONFIG_VERSION = 1
KELVIN_OFFSET = 273.15


class HookError(RuntimeError):
    """Raised when an exchange cannot be completed safely."""


def _mapping(value: Any, location: str) -> Dict[str, Any]:
    if not isinstance(value, dict):
        raise HookError(f"{location} must be an object")
    return value


def _list(value: Any, location: str) -> List[Any]:
    if not isinstance(value, list):
        raise HookError(f"{location} must be an array")
    return value


def _string(value: Any, location: str) -> str:
    if not isinstance(value, str) or not value:
        raise HookError(f"{location} must be a non-empty string")
    return value


def _finite(value: Any, location: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise HookError(f"{location} must be a number")
    parsed = float(value)
    if not math.isfinite(parsed):
        raise HookError(f"{location} must be finite")
    return parsed


def _nonnegative(value: Any, location: str) -> float:
    parsed = _finite(value, location)
    if parsed < 0.0:
        raise HookError(f"{location} must be non-negative")
    return parsed


def _integer(value: Any, location: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise HookError(f"{location} must be an integer")
    return value


def _exact_path(value: Any, location: str) -> str:
    path = _string(value, location)
    if not path.startswith("/") or path == "/":
        raise HookError(f"{location} must be an absolute component path")
    parts = path.split("/")[1:]
    if any(
        not part or part in {".", "..", "*", "**"}
        for part in parts
    ):
        raise HookError(f"{location} must be exact and canonical")
    return path


def load_json(path: Path, label: str) -> Dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as stream:
            return _mapping(json.load(stream), label)
    except FileNotFoundError as exc:
        raise HookError(f"missing {label}: {path}") from exc
    except json.JSONDecodeError as exc:
        raise HookError(f"invalid JSON in {label} {path}: {exc}") from exc


def validate_protocol(document: Dict[str, Any], location: str) -> None:
    protocol = _mapping(document.get("protocol"), f"{location}.protocol")
    if protocol.get("name") != PROTOCOL_NAME:
        raise HookError(
            f"{location}.protocol.name must be {PROTOCOL_NAME!r}"
        )
    if protocol.get("version") != PROTOCOL_VERSION:
        raise HookError(
            f"{location}.protocol.version must be {PROTOCOL_VERSION}"
        )


def validate_request(document: Dict[str, Any], phase: str) -> Dict[str, Any]:
    validate_protocol(document, "request")
    if document.get("phase") != phase:
        raise HookError(
            f"request phase {document.get('phase')!r} does not match {phase!r}"
        )
    if document.get("temperature_unit") != "celsius":
        raise HookError("request.temperature_unit must be 'celsius'")

    window = _mapping(document.get("window"), "request.window")
    start_ps = _integer(window.get("start_ps"), "request.window.start_ps")
    end_ps = _integer(window.get("end_ps"), "request.window.end_ps")
    if start_ps < 0 or end_ps < start_ps:
        raise HookError("request window must be non-negative and ordered")

    components = _list(document.get("components"), "request.components")
    if phase == "init" and components:
        raise HookError("init request must not contain component samples")

    seen = set()
    validated_components = []
    for index, value in enumerate(components):
        location = f"request.components[{index}]"
        component = _mapping(value, location)
        path = _exact_path(component.get("path"), f"{location}.path")
        if path in seen:
            raise HookError(f"duplicate request component path {path!r}")
        seen.add(path)
        if component.get("scope") != "subtree":
            raise HookError(f"{location}.scope must be 'subtree'")

        dynamic_w = _nonnegative(
            component.get("dynamic_w"), f"{location}.dynamic_w"
        )
        leakage_w = _nonnegative(
            component.get("leakage_w"), f"{location}.leakage_w"
        )
        total_w = _nonnegative(
            component.get("total_w"), f"{location}.total_w"
        )
        tolerance = max(1.0e-12, abs(total_w) * 1.0e-9)
        if abs(total_w - dynamic_w - leakage_w) > tolerance:
            raise HookError(
                f"{location}.total_w does not equal dynamic_w + leakage_w"
            )
        temperature_c = _finite(
            component.get("temperature_c"), f"{location}.temperature_c"
        )
        if temperature_c <= -KELVIN_OFFSET:
            raise HookError(
                f"{location}.temperature_c must be above absolute zero"
            )
        validated_components.append(
            {
                "path": path,
                "dynamic_w": dynamic_w,
                "leakage_w": leakage_w,
                "total_w": total_w,
                "temperature_c": temperature_c,
            }
        )

    return {
        "phase": phase,
        "start_ps": start_ps,
        "end_ps": end_ps,
        "components": validated_components,
    }


def validate_hook_config(document: Dict[str, Any], path: Path) -> Dict[str, Any]:
    discriminator = _mapping(document.get("hook"), "hook configuration.hook")
    if discriminator.get("name") != HOOK_CONFIG_NAME:
        raise HookError(
            f"hook configuration name must be {HOOK_CONFIG_NAME!r}"
        )
    if discriminator.get("version") != HOOK_CONFIG_VERSION:
        raise HookError(
            f"hook configuration version must be {HOOK_CONFIG_VERSION}"
        )

    def resolved_path(name: str) -> Path:
        value = Path(_string(document.get(name), f"hook configuration.{name}"))
        if not value.is_absolute():
            value = path.parent / value
        return value.resolve()

    poll_seconds = _finite(
        document.get("poll_seconds", 0.02),
        "hook configuration.poll_seconds",
    )
    timeout_seconds = _finite(
        document.get("timeout_seconds", 180.0),
        "hook configuration.timeout_seconds",
    )
    if poll_seconds <= 0.0 or timeout_seconds <= 0.0:
        raise HookError("hook polling and timeout values must be positive")

    default_power_w = document.get("default_power_w")
    if default_power_w is not None:
        default_power_w = _nonnegative(
            default_power_w, "hook configuration.default_power_w"
        )

    return {
        "system_config": resolved_path("system_config"),
        "floorplan": resolved_path("floorplan"),
        "power_trace": resolved_path("power_trace"),
        "temperature_output": resolved_path("temperature_output"),
        "temperature_history": resolved_path("temperature_history"),
        "poll_seconds": poll_seconds,
        "timeout_seconds": timeout_seconds,
        "default_power_w": default_power_w,
    }


def parse_temperature_rows(
    path: Path, expected_entries: List[str]
) -> List[Tuple[float, List[float]]]:
    if not path.exists():
        return []

    header_entries: Optional[List[str]] = None
    rows: List[Tuple[float, List[float]]] = []
    with path.open("r", encoding="utf-8") as stream:
        while True:
            line = stream.readline()
            if not line:
                break
            if not line.endswith("\n"):
                break
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("%"):
                fields = stripped.split()
                if len(fields) >= 2 and fields[1] == "Time(s)":
                    parsed = []
                    for field in fields[2:]:
                        if not field.endswith("(K)"):
                            raise HookError(
                                f"malformed Tflp header field {field!r} in {path}"
                            )
                        parsed.append(field[:-3])
                    header_entries = parsed
                continue

            fields = stripped.split()
            if len(fields) != len(expected_entries) + 1:
                raise HookError(
                    f"{path}: expected time plus {len(expected_entries)} "
                    f"temperatures, got {len(fields)} fields"
                )
            try:
                values = [float(field) for field in fields]
            except ValueError as exc:
                raise HookError(f"{path}: non-numeric Tflp row") from exc
            if any(not math.isfinite(value) for value in values):
                raise HookError(f"{path}: non-finite Tflp value")
            temperatures_k = values[1:]
            if any(value <= 0.0 for value in temperatures_k):
                raise HookError(f"{path}: temperatures must be positive Kelvin")
            rows.append((values[0], temperatures_k))

    if header_entries is not None and header_entries != expected_entries:
        raise HookError(
            "Tflp header does not match generated floorplan order "
            f"(expected {expected_entries!r}, got {header_entries!r})"
        )
    return rows


def wait_for_temperature_row(
    path: Path,
    expected_entries: List[str],
    previous_count: int,
    poll_seconds: float,
    timeout_seconds: float,
) -> List[float]:
    deadline = time.monotonic() + timeout_seconds
    while True:
        rows = parse_temperature_rows(path, expected_entries)
        if len(rows) > previous_count:
            return rows[previous_count][1]
        if time.monotonic() >= deadline:
            raise HookError(
                f"timed out after {timeout_seconds:g}s waiting for "
                f"Tflp row {previous_count + 1} in {path}"
            )
        time.sleep(poll_seconds)


def append_power_slot(path: Path, values: Iterable[float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as stream:
        write_slot(stream, values)


def append_termination_slot(path: Path, width: int) -> None:
    last_values = None
    if path.exists():
        with path.open("r", encoding="utf-8") as stream:
            for line in stream:
                if line.endswith("\n") and line.strip():
                    try:
                        last_values = [float(field) for field in line.split()]
                    except ValueError:
                        last_values = None
    if (
        last_values is not None
        and len(last_values) == width
        and all(value == -1.0 for value in last_values)
    ):
        return
    append_power_slot(path, [-1.0] * width)


def component_temperatures(
    document: Dict[str, Any],
    floorplan_entries: List[str],
    temperatures_k: List[float],
) -> List[Dict[str, Any]]:
    by_element = dict(zip(floorplan_entries, temperatures_k))
    geometry = document["geometry"]
    updates = []
    for component in thermal_components(document):
        weighted_sum = 0.0
        total_area = 0.0
        for element_name in component["floorplan_elements"]:
            flat_name = flattened_floorplan_name(element_name)
            if flat_name not in by_element:
                raise HookError(
                    f"thermal mapping references absent floorplan element "
                    f"{element_name!r}"
                )
            shape = geometry_entry(geometry, element_name)["shape"]
            area = float(shape[0]) * float(shape[1])
            weighted_sum += by_element[flat_name] * area
            total_area += area
        if total_area <= 0.0:
            raise HookError(
                f"thermal mapping for {component['path']!r} has zero area"
            )
        temperature_c = weighted_sum / total_area - KELVIN_OFFSET
        updates.append(
            {
                "path": component["path"],
                "temperature_c": temperature_c,
            }
        )
    return updates


def write_history(
    path: Path,
    phase: str,
    start_ps: int,
    end_ps: int,
    powers_by_path: Dict[str, float],
    updates: List[Dict[str, Any]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    needs_header = not path.exists() or path.stat().st_size == 0
    with path.open("a", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        if needs_header:
            writer.writerow(
                [
                    "phase",
                    "start_ps",
                    "end_ps",
                    "component_path",
                    "power_w",
                    "temperature_c",
                ]
            )
        for update in updates:
            writer.writerow(
                [
                    phase,
                    start_ps,
                    end_ps,
                    update["path"],
                    powers_by_path.get(update["path"], ""),
                    f"{update['temperature_c']:.17g}",
                ]
            )
        stream.flush()
        os.fsync(stream.fileno())


def atomic_json(path: Path, document: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(
        path.name + f".tmp.{os.getpid()}"
    )
    try:
        with temporary.open("w", encoding="utf-8") as stream:
            json.dump(document, stream, indent=2, sort_keys=True)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(str(temporary), str(path))
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def response(phase: str, updates: List[Dict[str, Any]]) -> Dict[str, Any]:
    return {
        "protocol": {
            "name": PROTOCOL_NAME,
            "version": PROTOCOL_VERSION,
        },
        "phase": phase,
        "temperature_unit": "celsius",
        "temperatures": updates,
    }


def exchange(
    request: Dict[str, Any],
    config: Dict[str, Any],
    document: Dict[str, Any],
    floorplan_entries: List[str],
) -> List[Dict[str, Any]]:
    declared = thermal_components(document)
    declared_paths = {component["path"] for component in declared}
    samples_by_path = {
        component["path"]: component
        for component in request["components"]
    }
    actual_paths = set(samples_by_path)
    if actual_paths != declared_paths:
        missing = declared_paths - actual_paths
        extra = actual_paths - declared_paths
        details = []
        if missing:
            details.append("missing: " + ", ".join(sorted(missing)))
        if extra:
            details.append("undeclared: " + ", ".join(sorted(extra)))
        raise HookError("request component mismatch (" + "; ".join(details) + ")")

    power_by_column = {
        component["power_column"]: samples_by_path[component["path"]]["total_w"]
        for component in declared
    }
    columns = power_columns(document)
    raw_values = [power_by_column[column] for column in columns]
    power_sources = build_power_sources(document)
    values = adapt_slot(
        raw_values,
        columns,
        floorplan_entries,
        power_sources,
        config["default_power_w"],
        config["power_trace"],
        1,
    )

    existing_rows = parse_temperature_rows(
        config["temperature_output"], floorplan_entries
    )
    append_power_slot(config["power_trace"], values)
    temperatures_k = wait_for_temperature_row(
        config["temperature_output"],
        floorplan_entries,
        len(existing_rows),
        config["poll_seconds"],
        config["timeout_seconds"],
    )
    updates = component_temperatures(
        document, floorplan_entries, temperatures_k
    )
    write_history(
        config["temperature_history"],
        request["phase"],
        request["start_ps"],
        request["end_ps"],
        {
            path: sample["total_w"]
            for path, sample in samples_by_path.items()
        },
        updates,
    )
    return updates


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Exchange GVSoC power and 3D-ICE floorplan temperatures."
    )
    parser.add_argument(
        "--phase", required=True, choices=["init", "update", "final"]
    )
    parser.add_argument("--request", required=True)
    parser.add_argument("--response", required=True)
    parser.add_argument("--config", required=True)
    return parser.parse_args()


def run(args: argparse.Namespace) -> int:
    request_path = Path(args.request).resolve()
    response_path = Path(args.response).resolve()
    config_path = Path(args.config).resolve()

    request_document = validate_request(
        load_json(request_path, "power-hook request"), args.phase
    )
    config = validate_hook_config(
        load_json(config_path, "power-hook configuration"), config_path
    )
    document = load_contract(config["system_config"])

    floorplan_entries = parse_floorplan_entries(config["floorplan"])
    power_sources = build_power_sources(document)
    validate_floorplan_entries(floorplan_entries, power_sources)

    if args.phase == "init":
        # Validate an already-created Tflp header when available. The server
        # creates it before advertising readiness.
        parse_temperature_rows(
            config["temperature_output"], floorplan_entries
        )
        temperature = initial_temperature_c(document)
        updates = [
            {
                "path": component["path"],
                "temperature_c": temperature,
            }
            for component in thermal_components(document)
        ]
        write_history(
            config["temperature_history"],
            "init",
            0,
            0,
            {},
            updates,
        )
    elif request_document["end_ps"] > request_document["start_ps"]:
        updates = exchange(
            request_document, config, document, floorplan_entries
        )
    else:
        updates = []

    if args.phase == "final":
        append_termination_slot(
            config["power_trace"], len(floorplan_entries)
        )

    atomic_json(response_path, response(args.phase, updates))
    print(
        f"[3dice-power-hook] {args.phase}: "
        f"{len(request_document['components'])} power sample(s), "
        f"{len(updates)} temperature(s)",
        flush=True,
    )
    return 0


def main() -> int:
    args = parse_args()
    try:
        return run(args)
    except KeyboardInterrupt:
        return 130
    except Exception as exc:
        print(
            f"3dice_power_hook.py: error: {exc}",
            file=sys.stderr,
            flush=True,
        )
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
